Federation wip
mpaulgreen/kong-demo pull request #14
Opened 2022-05-12 13:29 UTC by cmwylie19

This PR includes Grafana Dashboards, and a `kong-mesh-federation.md` doc.

The markdown goes into:
- ServiceMonitor and ClusterRoles to Federate Kong Prometheus to OpenShift Prometheus with deduplicated data
- PrometheusRules to trigger alerts
- Installation of the Grafana Operator and creation of dashboards (Kong's Dashboards)

2022-05-13 14:31 UTC, mpaulgreen commented
@cmwylie19 I think this is still in progress?

2022-05-13 18:12 UTC, cmwylie19 commented
> 



> @cmwylie19 I think this is still in progress?

Hey @mpaulgreen, i would say this is ready to merge.

2022-05-17 10:14 UTC, ruromero requested changes
Hey @cmwylie19 it works but I have some suggestions, improvements and corrections
Great work

2022-05-17 10:14 UTC, ruromero commented on kong-mesh-federation.md
> +open [Prometheus Alerts](http://localhost:9090/alerts)
Suggestion, use the REST api

```
http localhost:9090/api/v1/alerts | jq '.data.alerts | .[] | select(.labels.alertname | contains("KongDemoCacheDown"))'   
{
  "labels": {
    "alertname": "KongDemoCacheDown",
    "severity": "critical"
  },
  "annotations": {
    "description": "Demo Cache pod has not been ready the defined time period.",
    "summary": "Demo Cache is down."
  },
  "state": "firing",
  "activeAt": "2022-05-17T09:55:00.456457993Z",
  "value": "1e+00"
}
```

2022-05-17 10:14 UTC, ruromero commented on kong-mesh-federation.md
> +Since Grafana is now depricated in OCP 4.10, we are using the Grafana Operator for ease of use and configuration.
```suggestion
Since Grafana is now deprecated in OCP 4.10, we are using the Grafana Operator for ease of use and configuration.
```

2022-05-17 10:14 UTC, ruromero commented on kong-mesh-federation.md
> +  creationTimestamp: null
```suggestion
```

2022-05-17 10:14 UTC, ruromero commented on kong-mesh-federation.md
> +
you're missing the following:

```
oc delete clusterrolebinding cluster-monitoring-view   
oc delete clusterrolebinding kong-prom-binding
oc delete clusterrole kong-prom 

oc delete ns grafana
```

2022-05-17 12:56 UTC, cmwylie19 commented on kong-mesh-federation.md
> +oc delete po --force --grace-period=0 -n kuma-demo -l app=redis
This is necessary to trigger the alert from the PrometheusRule. We want to go ahead and take it down to demo the alert to the user.

2022-05-17 13:02 UTC, cmwylie19 commented on kong-mesh-federation.md
> +Remove the Sidecars (Still working through a solution with [sidecars](https://support.f5.com/csp/article/K03234274))
Got it, if we want the same dashboards in 2 places that works for me. I didn't bother with the Kong Dashboards because they were reproduced with GrafanaDashboard CRDs. Didn't want to duplicate work. I will add in this suggestion.

2022-05-17 13:06 UTC, cmwylie19 commented on kong-mesh-federation.md
> +open [Prometheus Alerts](http://localhost:9090/alerts)
The second reason i didn't want to use the rest API is due to the nature of the delayed process between configuring the PrometheusRule and the actual firing of the alert. 

My concerned is if they quickly run the curl- the alerts will come back empty. The user may think the rule is not triggering. 

The port-forward will cause them to take more time between and likely see the alert go from pending to firing.

Just my two cents, but that was my reasoning behind that.

2022-05-17 14:04 UTC, ruromero commented on kong-mesh-federation.md
> +oc delete po --force --grace-period=0 -n kuma-demo -l app=redis
I mean the delete pods, the scale should delete the pods already

2022-05-17 14:05 UTC, ruromero commented on kong-mesh-federation.md
> +Remove the Sidecars (Still working through a solution with [sidecars](https://support.f5.com/csp/article/K03234274))
Thanks

2022-05-17 14:06 UTC, ruromero commented on kong-mesh-federation.md
> +open [Prometheus Alerts](http://localhost:9090/alerts)
IMO it's the same experience as if opening the UI and not seeing the alert. It's more of a personal taste

2022-05-17 14:13 UTC, cmwylie19 commented on kong-mesh-federation.md
> +oc delete po --force --grace-period=0 -n kuma-demo -l app=redis
got it, the idea. This can be removed.

2022-05-17 14:13 UTC, cmwylie19 commented on kong-mesh-federation.md
> +oc delete po --force --grace-period=0 -n kuma-demo -l app=redis
updated.

2022-05-17 15:32 UTC, ruromero approved these changes
LGTM thanks

2022-05-17 15:51 UTC, merged